import AppKit
import PegCore

@MainActor
final class ClipboardMonitor {
    private var store: ClipboardStore
    private let pasteboard = NSPasteboard.general
    private var changeCount: Int
    private var timer: Timer?
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    var entries: [ClipEntry] {
        store.entries
    }

    init() {
        store = ClipboardStore.load(from: PegPaths.clipboardFile)
        changeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.poll()
            }
        }
    }

    func copy(_ entry: ClipEntry) {
        pasteboard.clearContents()
        pasteboard.setString(entry.text, forType: .string)
        changeCount = pasteboard.changeCount
        store.add(entry.text)
        save()
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        let types = pasteboard.types ?? []
        guard !types.contains(where: { ignoredTypes.contains($0.rawValue) }) else { return }
        guard let text = pasteboard.string(forType: .string) else { return }
        store.add(text)
        save()
    }

    private func save() {
        do {
            try store.save(to: PegPaths.clipboardFile)
        } catch {
            NSLog("Peg: failed to save clipboard history: %@", error.localizedDescription)
        }
    }
}
